### ISSUE TITLE
请问下第八步部署的问题

### ISSUE THREAD

**Issue by kimura0321** [benx1n/wows-stats-bot#2]
请问下，
步骤8中，
按照步骤做复制文本路径后运行，
仍然显示：
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

文本是这样的：

done
#
# To activate this environment, use
#
#     $ conda activate py3.8
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(py3.8) C:\Users\Admin>activate py3.8

(py3.8) C:\Users\Admin>conda.bat activate py3.8

(py3.8) C:\Users\Admin>cd D:\HoshinoBot

(py3.8) C:\Users\Admin>activate py3.8

(py3.8) C:\Users\Admin>conda.bat activate py3.8

(py3.8) C:\Users\Admin>cd D:\HoshinoBot

(py3.8) C:\Users\Admin>pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by benx1n** [comment]
请确认你当前文件夹下是否存在requirements.txt，大多数原因是你clone在了同名文件夹下而没进入子文件夹
还有就是请在提交log时使用代码块 否则会被格式化

**Comment by kimura0321** [comment]
我在D盘创建了HoshinoBot文件夹，
此时路径为：D:\HoshinoBot，
而且HoshinoBot文件夹里面有requirements.txt文件，
我跟着1-7步做的没问题，
但是这个第八步，
我把D:\HoshinoBot这个路径替换掉了【您的xxx】这些文字，
仍然显示errno2这个错误提示。
请问我的路径应该怎么写啊

**Comment by kimura0321** [comment]
HoshinoBot文件夹下有这些文件：

hoshino

.gitignore

LICENSE

README

requirements

run

这个路径是对的呀，为什么还是说 No such file or directory: 'requirements.txt'

**Comment by kimura0321** [comment]
而且不止我遇到这个问题，群里还有2个人也是同样的问题，请帮下忙，谢谢

**Comment by benx1n** [comment]
你没有切换成功路径
跨盘符切换时需要先输入对应盘符，再cd
例如
D:
cd HoshinoBot
