### ISSUE TITLE
ocr代码功能缺失

### ISSUE THREAD

**Issue by MackerelFish** [benx1n/wows-stats-bot#7]
缺少Key值ocr_offline
![STAIH M}7A1U$6XWR2GUH07](https://user-images.githubusercontent.com/49937260/221485883-c4e4ec3f-76ca-4909-a248-59bc74177947.png)
![F%I@V$M6%F16IZ0J`1RKX45](https://user-images.githubusercontent.com/49937260/221485930-e834c4a7-e9bb-4071-b3a7-87a1acd906c5.png)

**Comment by benx1n** [comment]
fix on e3e34e468f8dec51875d5283fa26be0c36c00bcb
